name: courtship
dependencies:
    - python=2.7
    - alabaster
    - h5py
    - matplotlib
    - numpy
    - pandas
    - pyqt
    - pytz
    - qt
    - scikit-image
    - scikit-learn
    - scipy
    - sphinx
    - sphinxcontrib
    - xlsxwriter
    - xlrd
    - pip:
        - motmot.FlyMovieFormat
        - pycircstat
        - recommonmark
        - pyqtgraph
        - nose
